server:
  port: 8083

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: INTERN
          uri: lb://INTERN
          predicates:
            - Path=/api/avis/**
        - id: FINANCE
          uri: lb://FINANCE
          predicates:
            - Path=/api/infraction/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

